services:
  - type: web
    name: realestate-api
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DB_HOST
        value: realestate-db.render.com
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: VyXkzBXZvKymGWQFcTScyCiOqtOueIOQ
      - key: DB_DATABASE
        value: realestate_db
      - key: JWT_SECRET
        value: jashdj1236876asdgjhvh@!!@!@jhasdjhgajdahgdfhgbvxcbzchfFFFASYTFGHFGHfgDGFGAHDFTYQWEGHFXCHGDDTfdagfsdgdywreqwgf/!@!@!@!@@!@^^&&%$^&*&*%^$XZCDSQEqdxjHJHJGHG
      - key: PORT
        value: 5000



